package enums;

public enum GameAction {

	NOTHING,
	AT_CHAR_SELECT_SCREEN,
	AT_STAGE_SELECT_SCREEN,
	AT_WIN_SCREEN,
	AT_FERVER_TIME,
	WAITING_FOR_CHAR_SELECT_SCREEN,
	WAITING_FOR_MUSIC_START,
	DANCING;	
}
